<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\LearningController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ScormPlayerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SectionController as AdminSectionController;
use App\Http\Controllers\Admin\MaterialController as AdminMaterialController;
use App\Http\Controllers\Admin\ScormController as AdminScormController;
use App\Http\Controllers\Admin\CourseController as AdminCourseController;
use App\Http\Controllers\Admin\LessonController as AdminLessonController;
use App\Http\Controllers\Admin\JournalController as AdminJournalController;
Route::get('/',[HomeController::class,'index'])->name('home');
Route::get('/section/{section:slug}',[SectionController::class,'show'])->name('section.show');
Route::get('/material/{material:slug}',[MaterialController::class,'show'])->name('material.show');
Route::get('/course/{course:slug}',[CourseController::class,'show'])->name('courses.show');
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'form'])->name('login');Route::post('/login',[AuthController::class,'login'])->name('login.post');});
Route::post('/logout',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function(){
 Route::post('/course/{course:slug}/enroll',[CourseController::class,'enroll'])->name('courses.enroll');
 Route::get('/my-courses',[LearningController::class,'myCourses'])->name('learning.my-courses');
 Route::get('/lesson/{lesson}',[LearningController::class,'lesson'])->name('learning.lesson');
 Route::post('/lesson/{lesson}/complete',[LearningController::class,'complete'])->name('learning.lesson.complete');
 Route::get('/scorm/{scorm}/launch',[ScormPlayerController::class,'launch'])->name('scorm.launch');
 Route::get('/scorm/attempt/{attempt}/state',[ScormPlayerController::class,'state'])->name('scorm.state');
 Route::post('/scorm/attempt/{attempt}/commit',[ScormPlayerController::class,'commit'])->name('scorm.commit');
});
Route::prefix('admin')->name('admin.')->middleware(['auth','admin'])->group(function(){
 Route::get('/',[DashboardController::class,'index'])->name('dashboard');
 Route::resource('sections',AdminSectionController::class)->except('show');
 Route::resource('materials',AdminMaterialController::class)->except('show');
 Route::resource('courses',AdminCourseController::class)->except('show');
 Route::resource('courses.lessons',AdminLessonController::class)->except('show');
 Route::get('/journal',[AdminJournalController::class,'index'])->name('journal.index');
 Route::get('/journal/{course}',[AdminJournalController::class,'show'])->name('journal.show');
 Route::get('/scorm',[AdminScormController::class,'index'])->name('scorm.index');
 Route::post('/scorm',[AdminScormController::class,'store'])->name('scorm.store');
 Route::delete('/scorm/{scorm}',[AdminScormController::class,'destroy'])->name('scorm.destroy');
});
