<?php
namespace App\Http\Controllers;
use App\Models\Certificate;use App\Models\Course;use App\Models\Enrollment;use App\Models\Group;use App\Models\LessonProgress;use Illuminate\Http\Request;
class CabinetController extends Controller {
 public function index(Request $r){$u=$r->user();if($u->isAdmin())return redirect()->route('admin.dashboard');if($u->role==='teacher')return $this->teacher($r);return $this->student($r);}
 private function student(Request $r){$u=$r->user();$enrollments=Enrollment::with(['course.lessons'])->where('user_id',$u->id)->latest('enrolled_at')->get();$progress=LessonProgress::where('user_id',$u->id)->get()->keyBy('lesson_id');$stats=[];foreach($enrollments as $e){$ids=$e->course->lessons->where('is_active',true)->pluck('id');$done=$progress->whereIn('lesson_id',$ids)->whereIn('status',['completed','passed'])->count();$stats[$e->id]=['done'=>$done,'total'=>$ids->count(),'percent'=>$ids->count()?round($done*100/$ids->count()):0];}$groups=$u->groups()->with('curator')->get();$certificates=Certificate::with('course')->where('user_id',$u->id)->latest('issued_at')->limit(5)->get();return view('cabinet.student',compact('u','enrollments','progress','stats','groups','certificates'));}
 private function teacher(Request $r){$u=$r->user();$courses=Course::withCount('enrollments')->with('section')->where('instructor_id',$u->id)->orderBy('title')->get();$groups=Group::withCount('users')->with('courses')->where('curator_id',$u->id)->orderBy('name')->get();return view('cabinet.teacher',compact('u','courses','groups'));}
 public function teacherJournal(Request $r,Course $course){abort_unless($r->user()->role==='teacher'&&$course->instructor_id===$r->user()->id,403);$course->load(['lessons'=>fn($q)=>$q->where('is_active',true)->orderBy('sort_order')]);$enrollments=Enrollment::with('user')->where('course_id',$course->id)->orderBy('enrolled_at')->get();$progress=LessonProgress::whereIn('user_id',$enrollments->pluck('user_id'))->whereIn('lesson_id',$course->lessons->pluck('id'))->get()->keyBy(fn($p)=>$p->user_id.':'.$p->lesson_id);return view('cabinet.teacher-journal',compact('course','enrollments','progress'));}
}
