<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\Group;use App\Models\User;use Illuminate\Http\Request;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use ZipArchive;
class UserController extends Controller{
 public function index(Request $r){$q=User::with('groups');if($r->filled('q')){$s=$r->q;$q->where(fn($x)=>$x->where('name','like',"%$s%")->orWhere('email','like',"%$s%"));}if($r->filled('role'))$q->where('role',$r->role);if($r->filled('group_id'))$q->whereHas('groups',fn($x)=>$x->where('groups.id',$r->group_id));return view('admin.users.index',['users'=>$q->orderBy('name')->paginate(40)->withQueryString(),'groups'=>Group::orderBy('name')->get()]);}
 public function create(){return view('admin.users.form',['user'=>new User,'groups'=>Group::orderBy('name')->get()]);}
 public function store(Request $r){$d=$this->data($r);$d['password']=Hash::make($r->input('password')?:Str::random(12));$u=User::create($d);$u->groups()->sync($r->input('group_ids',[]));return redirect()->route('admin.users.index')->with('success','Пользователь создан');}
 public function edit(User $user){return view('admin.users.form',['user'=>$user,'groups'=>Group::orderBy('name')->get()]);}
 public function update(Request $r,User $user){$d=$this->data($r,$user);if($r->filled('password'))$d['password']=Hash::make($r->password);$user->update($d);$user->groups()->sync($r->input('group_ids',[]));return redirect()->route('admin.users.index')->with('success','Пользователь обновлён');}
 public function destroy(User $user){abort_if($user->id===auth()->id(),422,'Нельзя удалить текущего пользователя');$user->delete();return back()->with('success','Пользователь удалён');}
 public function bulkGroup(Request $r){$d=$r->validate(['user_ids'=>'required|array','user_ids.*'=>'exists:users,id','group_id'=>'required|exists:groups,id','mode'=>'required|in:add,move,remove']);$users=User::whereIn('id',$d['user_ids'])->get();foreach($users as $u){if($d['mode']==='move')$u->groups()->sync([$d['group_id']]);elseif($d['mode']==='remove')$u->groups()->detach($d['group_id']);else $u->groups()->syncWithoutDetaching([$d['group_id']]);}return back()->with('success','Групповая операция выполнена');}
 public function import(Request $r){$r->validate(['file'=>'required|file|mimes:csv,txt,xlsx','group_id'=>'nullable|exists:groups,id']);$rows=$this->rows($r->file('file')->getRealPath(),strtolower($r->file('file')->getClientOriginalExtension()));$count=0;foreach($rows as $row){$name=trim($row['name']??$row['fio']??'');$email=trim($row['email']??'');if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL))continue;$role=in_array(($row['role']??'student'),['student','teacher','editor','admin'])?$row['role']:'student';$u=User::updateOrCreate(['email'=>$email],['name'=>$name,'role'=>$role,'password'=>Hash::make($row['password']??Str::random(12))]);if($r->group_id)$u->groups()->syncWithoutDetaching([$r->group_id]);$count++;}return back()->with('success','Импортировано пользователей: '.$count);}
 private function data(Request $r,?User $u=null){return $r->validate(['name'=>'required|max:255','email'=>'required|email|max:255|unique:users,email'.($u?','.$u->id:''),'role'=>'required|in:student,teacher,editor,admin','password'=>($u?'nullable':'nullable').'|min:8']);}
 private function rows($path,$ext){return $ext==='xlsx'?$this->xlsx($path):$this->csv($path);}
 private function csv($path){$h=fopen($path,'r');$first=fgets($h);rewind($h);$delimiter=substr_count($first,';')>substr_count($first,',')?';':',';$headers=array_map(fn($v)=>strtolower(trim($v)),fgetcsv($h,0,$delimiter));$rows=[];while(($r=fgetcsv($h,0,$delimiter))!==false){$r=array_pad($r,count($headers),null);$rows[]=array_combine($headers,array_slice($r,0,count($headers)));}fclose($h);return $rows;}
 private function xlsx($path){$zip=new ZipArchive;if($zip->open($path)!==true)return[];$shared=[];$s=$zip->getFromName('xl/sharedStrings.xml');if($s){$xml=simplexml_load_string($s);foreach($xml->si as $si)$shared[]=trim((string)$si->t ?: implode('',array_map(fn($x)=>(string)$x->t,iterator_to_array($si->r))));}$sheet=$zip->getFromName('xl/worksheets/sheet1.xml');$zip->close();if(!$sheet)return[];$xml=simplexml_load_string($sheet);$rows=[];$headers=[];foreach($xml->sheetData->row as $ri=>$row){$vals=[];foreach($row->c as $c){$v=(string)$c->v;$vals[]=(string)$c['t']==='s'?($shared[(int)$v]??''):$v;}if(!$headers){$headers=array_map(fn($v)=>strtolower(trim($v)),$vals);continue;}$vals=array_pad($vals,count($headers),null);$rows[]=array_combine($headers,array_slice($vals,0,count($headers)));}return $rows;}
}
